"""Add file_path column

Revision ID: 311fc11ecf89
Revises: 
Create Date: 2023-12-13 20:50:40.945058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311fc11ecf89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
